import Head from "next/head";
import Image from "next/image";

import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";
import { useEffect, useState } from "react";
import Projects from "@/components/projects";

export default function Home() {
  const [notes, setNotes] = useState<any[] | null>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Projects />

      <div>Content here</div>
    </>
  );
}
